# Generated by Django 4.2.3 on 2024-08-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_grade_student_test_grade_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
