# Generated by Django 4.2.3 on 2024-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='required_passes',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='required_passes',
            field=models.IntegerField(default=2),
        ),
    ]
