# Generated by Django 4.2.3 on 2023-09-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_skill_required_passes_skilllevel_required_passes'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
